---
title: "Gradient Descent"
output: html_document
---

## (a)
```{r}
g <- function(w0, w1) {
  return(
    2 + w0 + w1 + 3*w0*w1 + 7.5*w0^2 + 1.25*w1^2
  )
}

g_prime <- function(w0, w1) {
  return(
    rbind(c(
      1 + 5*w0 + 3*w1,
      1 + 3*w0 + 2.5*w1
    ))
  )
}

C <- rbind(
  c(7.5, 2),
  c(1, 1.25)
)
w0 <- rbind(c(3,3))
current <- w0
alpha <- 0.1
tol <- 10^-5
count <- 0

weight_history <- rbind(c(0,0))
cost_history <- numeric(0)
repeat{
  
  cw1 <- current[1,1]
  cw2 <- current[1,2]
  
  next_point <- current -  t(alpha * (solve(C)) %*% t(g_prime(cw1, cw2)))
  
  flag <- abs(g(next_point[1,1], next_point[1,2]) - g(current[1,1], current[1,2]))
  if(flag < tol){
    break
  }
  
  nw1 <- next_point[1,1]
  nw2 <- next_point[1,2]
  
  weight_history <- rbind(weight_history, next_point)
  cost_history <- c(cost_history, g(nw1, nw2))
  current <- rbind(c(nw1, nw2))
  count <- count + 1
}

xgrid <- ygrid <- seq(-10, 10, 0.1)
g_out <- outer(xgrid, ygrid, FUN = g)
contour(x = xgrid, y = ygrid, z = g_out) + points(weight_history[1:dim(weight_history)[1], 1], weight_history[1:dim(weight_history)[1], 2])
```
## (b)
```{r}
g <- function(w0, w1) {
  return(
    2 + w0 + w1 + 3*w0*w1 + 7.5*w0^2 + 1.25*w1^2
  )
}

g_prime <- function(w0, w1) {
  return(
    rbind(c(
      1 + 5*w0 + 3*w1,
      1 + 3*w0 + 2.5*w1
    ))
  )
}

C <- rbind(
  c(7.5, 2),
  c(1, 1.25)
)
w0 <- rbind(c(3,3))
current <- w0
alpha <- 0.1
tol <- 10^-1
count <- 0

weight_history <- rbind(c(0,0))
cost_history <- numeric(0)
repeat{
  
  cw1 <- current[1,1]
  cw2 <- current[1,2]
  
  next_point <- current -  t(alpha * (solve(C) %*% diag(2)) %*% t(g_prime(cw1, cw2)))
  
  flag <- abs(g(next_point[1,1], next_point[1,2]) - g(current[1,1], current[1,2]))
  if(flag < tol){
    break
  }
  
  nw1 <- next_point[1,1]
  nw2 <- next_point[1,2]
  
  weight_history <- rbind(weight_history, next_point)
  cost_history <- c(cost_history, g(nw1, nw2))
  current <- rbind(c(nw1, nw2))
  count <- count + 1
}

xgrid <- ygrid <- seq(-10, 10, 0.1)
g_out <- outer(xgrid, ygrid, FUN = g)
contour(x = xgrid, y = ygrid, z = g_out) + points(weight_history[1:dim(weight_history)[1], 1], weight_history[1:dim(weight_history)[1], 2])
```